#!/bin/sh
set -eux

version="1.2.2"
url="https://github.com/nix-community/nix-user-chroot/releases/download/${version}/nix-user-chroot-bin-${version}-$(arch)-unknown-linux-musl"

data_home="${XDG_DATA_HOME:-$HOME/.local/share}/nixbox"
nix_root="${data_home}/nix"
home_root="${data_home}/home"

die() {
    echo "$1"
    exit 1
}

run() {
    HOME=$home_root /tmp/nix-user-chroot "${nix_root}" "$@"
}

[[ -d "${data_home}" ]] && die "Nixbox already installed"

curl -L "${url}" --output /tmp/nix-user-chroot
chmod +x /tmp/nix-user-chroot
mkdir -p "${data_home}" "${nix_root}" "${home_root}"

cat | run sh <<EOF
set -eux

curl -L https://nixos.org/nix/install | sh /dev/stdin --no-daemon
EOF

echo "# BEGIN nixbox-install" >> $HOME/.bashrc
echo "export PATH=${data_home}/bin:\$PATH" >> $HOME/.bashrc
echo "# END nixbox-install" >> $HOME/.bashrc
