name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v23
    - uses: cachix/cachix-action@v12
      with:
        name: pinkwah
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Build brief-cli
      run: nix build .#brief-cli

    - name: Upload artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: brief-cli.zip
        path: result/bin/brief-cli
